package com.example.airquality;

// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;

import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;


@ExtendWith(SeleniumJupiter.class)
class ValidCityAQI_SeleniumIDE {
    ChromeDriver driver;
    public ValidCityAQI_SeleniumIDE(ChromeDriver driver) {
      this.driver = driver;
    }

    @Test
    void validCityAQI() {
        driver.get("http://localhost:8080/");

        assertThat(driver.getTitle(), is("Air Quality App"));
        {
            WebElement element = driver.findElement(By.cssSelector("h2"));
            String text = element.getText();
            assertThat(text, is("Welcome to the Air Quality Application!"));
        }
        {
            WebElement element = driver.findElement(By.cssSelector("h3"));
            String text = element.getText();
            assertThat(text, is("Please type the name of the city below:"));
        }

        driver.findElement(By.id("city_input")).click();
        driver.findElement(By.id("city_input")).sendKeys("London");

        {
            WebElement element = driver.findElement(By.cssSelector(".btn"));
            String text = element.getText();
            assertThat(text, is("Submit"));
        }

        driver.findElement(By.cssSelector(".btn")).click();

        {
            WebElement element = driver.findElement(By.cssSelector("h2"));
            String text = element.getText();
            assertThat(text, is("Air Quality Index for: LONDON"));
        }
        {
            WebElement element = driver.findElement(By.cssSelector("th:nth-child(5)"));
            String text = element.getText();
            assertThat(text, is("O3"));
        }

    }
}
